export const CodeError = {
  CREDENCIAIS_INVALIDAS: "CREDENCIAIS_INVALIDAS",
  CREDENCIAIS_EXPIRADAS: "CREDENCIAIS_EXPIRADAS",
  DADOS_INVALIDOS: "DADOS_INVALIDOS",
  NAO_ENCONTRADO: "NAO_ENCONTRADO",
  ERRO_INTERNO: "ERRO_INTERNO",
  ERRO_NAO_ESPECIFICADO: "ERRO_NAO_ESPECIFICADO",
} as const

export type CodeError = (typeof CodeError)[keyof typeof CodeError]
